version: "3.7"

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 9000:80
    depends_on:
      - backend
      - frontend
  db:
    image: postgres:alpine
    healthcheck:
      test: exit 0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data
  backend:
    build:
      context: backend
      dockerfile: ./Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/data
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
