"""empty message

Revision ID: 053e84c4483a
Revises:
Create Date: 2021-06-03 15:22:16.756744

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "053e84c4483a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("author", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("total_copies", sa.Integer(), nullable=True),
        sa.Column("available_copies", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.Column("admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "copy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("issuer", sa.Integer(), nullable=True),
        sa.Column("issued", sa.Boolean(), nullable=True),
        sa.Column("book", sa.Integer(), nullable=True),
        sa.Column("date_issued", sa.DateTime(), nullable=True),
        sa.Column("date_return", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["book"], ["book.id"], name="fk_copy_book_id_book"),
        sa.ForeignKeyConstraint(["issuer"], ["user.id"], name="fk_copy_user_id_issuer"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("copy")
    op.drop_table("user")
    op.drop_table("book")
    # ### end Alembic commands ###
